# Here we want to build an image where we compile the Go server, and then make a new docker image with the server and then run that
# We want to test if the ports inside of a container are unique to the container and thats it
# Do ports within this system clash with ports outside of the system too ?

# This a terrible idea because then we cant export them - we should just build the image with the files somehow