# Build the environment
FROM node:latest
WORKDIR /usr/app

# **** Maybe I can install the dev environment if it does not already exist ? (or maybe I can mount the volumes here instead ?)

# Start the dev server
CMD npm run dev