name: Deploy Markotplace

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
    # This workflow contains a single job called "build"
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy Markotplace
              uses: appleboy/ssh-action@v0.1.2
              with:
                  username: ${{secrets.SSH_USERNAME}}
                  host: ${{secrets.SSH_HOST}}
                  key: ${{secrets.SSH_KEY}}

                  script: |
                      cd Markotplace
                      scripts/deploy/production/stop.sh
                      git pull
                      scripts/deploy/production/deploy_ssl.sh
